CREATE USER airflow WITH PASSWORD 'CHANGE_ME_AIRFLOW_DB_PASSWORD';
CREATE DATABASE airflow OWNER airflow;

CREATE USER minhdwh WITH PASSWORD 'CHANGE_ME_DWH_PASSWORD';
CREATE DATABASE flight_dwh OWNER minhdwh;

CREATE DATABASE metabase OWNER postgres;
